### PR TITLE
feat(rules): validate the option examples for rules

### PR DESCRIPTION
**Pull request by cr7pt0gr4ph7**
## Summary

Extend the `rules_check` to:

(1) Ensure that configuration fragments are actually valid (and do not contain syntax or schema errors):

```rust
    /// ```json,options
    /// {
    ///     "options": { ... }
    /// }
    /// ```
```

(2) Validate rule examples that use a non-default configuration:

```rust
    /// ```json,options
    /// {
    ///     "options": { ... }
    /// }
    /// ```
    ///
    /// Invalid example for this configuration:
    ///
    /// ```js,expect_diagnostic,use_options
    /// import "invalid-import";
    /// ```
    ///
    /// Valid example for this configuration:
    ///
    /// ```json,use_options
    /// import "valid-import";
    /// ```
```

(3) Allow hiding lines from the output [like `rustdoc` does](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example) by prefixing them with `# `.

The corrresponding PR for [`biomejs/website`](https://github.com/biomejs/biome) is biomejs/biome#4542.

## Test Plan

- `pnpm codegen:rules`
- I manually inspected the documentation output generated for the website to ensure it is as intended.

### CODE REVIEW

**Comment by cr7pt0gr4ph7** [comment]
Note: This PR has merge conflicts because it needs to update `Cargo.toml` with new references to `biome` packages via specific Git commit SHA references. I'd recommend the following course of action:
1. Review biomejs/biome#4542 first until it is ready to merge
2. Let me integrate the requested changes into this PR
3. Review & merge biomejs/website#1442 so it supports the newly added doc features
4. Merge biomejs/biome#4542
5. Let the CI job update the commit hashes

**Review by ematipico — COMMENTED** [review]
You should run `pnpm codegen:rules` to check end result, and commit those files

**Comment by cr7pt0gr4ph7** [comment]
> You should run `pnpm codegen:rules` to check end result, and commit those files

Done :+1: Though the changes actually caused by this commit will only show up after biomejs/biome#4542 has been merged, because no `json,options` blocks exist before that.

**Comment by cr7pt0gr4ph7** [comment]
I re-ran `pnpm codegen:rules` after merging in the current changes from `main`. Should be ready for merge now!

**Comment by cr7pt0gr4ph7** [comment]
Just as a heads-up, there are problems in the output that are related to/caused by #1440. They are not _caused_ by the changes in this PR, but this PR manages to trigger some edge cases not hit before.

See for example https://deploy-preview-1442--biomejs.netlify.app/linter/rules/use-sorted-classes/#code-related:

image

**Comment by ematipico** [comment]
Yeah that's an issue of MDX and the use of JS templates inside the source code. I still have no idea how to fix it properly, but for now we need to live it with it

**Pull request merged**
