### PR TITLE
feat: support for graphql files

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR updates the frontend to support `.graphql` and `.gql` files, however the playground is throwing an error.

This is probably a bug  in core, I will look after it.

### CODE REVIEW

**Comment by Sec-ant** [comment]
We need to exlude graphql for the control flow graph: https://github.com/biomejs/website/blob/555dee4a30bdb234ac4c35349564d930f711bfcd/src/playground/workers/biomeWorker.ts#L222-L229

**Comment by Sec-ant** [comment]
I just realized we might have to exlude graphql from all the capabilities including formatting and linting, not only control flow graph. Otherwise those `workspace.` functions will throw errors:

https://github.com/biomejs/website/blob/555dee4a30bdb234ac4c35349564d930f711bfcd/src/playground/workers/biomeWorker.ts#L231-L261

**Comment by ematipico** [comment]
True, but would consider this an optimisation, not a blocker

**Comment by Sec-ant** [comment]
> True, but would consider this an optimisation, not a blocker

Yeah, but this problem prevents us from [using graphql code in the playground](https://deploy-preview-640--biomejs.netlify.app/playground/?files.main.gql=cQB1AGUAcgB5ACAAewAgAAoAIAAgAHYAaQBlAHcAZQByACAAewAgAAoAIAAgACAAIABsAG8AZwBpAG4ACgAgACAAfQAKAH0A), no?

**Comment by ematipico** [comment]
Good call on this one. I applied your suggestions and now we are getting the correct CST :)

**Comment by ematipico** [comment]
I am going to merge this, then land https://github.com/biomejs/biome/pull/3248 and then I will make another PR here to enable `pullDiagnostics`. That should give us a good output for the diagnostics.

**Pull request merged**
