### PR TITLE
Update no-non-null-assertion.md

### PR DESCRIPTION
**Pull request by iOnline247**
Fixed typo

### CODE REVIEW

**Comment by Sec-ant** [comment]
Thank you. The document is autogenerated from the doc comments in the source code. Do you want to send a PR in the main repo?

https://github.com/biomejs/biome/blob/78d70d2a075fee32d3694206ff4a6597aa551117/crates/biome_js_analyze/src/lint/style/no_non_null_assertion.rs

**Comment by iOnline247** [comment]
I've only dabbled lightly in Rust, but if I'm following, I just need to update the comment here?
https://github.com/biomejs/biome/blob/78d70d2a075fee32d3694206ff4a6597aa551117/crates/biome_js_analyze/src/lint/style/no_non_null_assertion.rs#L14-L47

If so, I can do that! :)

**Comment by Sec-ant** [comment]
> If so, I can do that! :)

Yes, just updating the comments will be fine.

**Comment by iOnline247** [comment]
Closing this in favor of: https://github.com/biomejs/biome/pull/2878

**Pull request closed without merging**
